let badWords = [
    // General Harm
    /\bkill yourself\b/i,
    /\bunalive yourself\b/i,
    /\bcommit suicide\b/i,
    /\bharm yourself\b/i,
    /\bend your life\b/i,
    /\bself harm\b/i,
    /\bself harming\b/i,
    /\bself destruct\b/i,
    /\bself destructive\b/i,
    /\bself inflict\b/i,
    /\bself inflicted\b/i,
    /\bself terminate\b/i,
    /\bself termination\b/i,
    /\bself annihilation\b/i,
    /\bself annihilate\b/i,
    /\bself destruction\b/i,
    /\bsuicidal\b/i,
    /\bsuicide\b/i,
    /\bend it all\b/i,
    /\bending it all\b/i,
    /\bexit life\b/i,
    /\bending my life\b/i,
    /\bnoose\b/i,
    /\bhanging\b/i,
    /\bdrown\b/i,
    /\boverdose\b/i,
    /\bjump off\b/i,
    /\bjumping off\b/i,
    /\bjump from\b/i,
    /\bjumping from\b/i,
    /\bstep in front\b/i,
    /\bstepping in front\b/i,
    /\btrain tracks\b/i,
    /\btrain accident\b/i,
    /\btrain collision\b/i,
    /\bpills\b/i,
    /\bdrug overdose\b/i,
    /\bgun\b/i,
    /\bfirearm\b/i,
    /\bweapon\b/i,
    /\bgas myself\b/i,
    /\bdrown myself\b/i,
    /\bcut myself\b/i,
    /\bstarve myself\b/i,
    /\bhang myself\b/i,
    /\bjump myself\b/i,
    /\boverdose myself\b/i,
    /\bend my life\b/i,
    /\bend your own life\b/i,
    /\bunalive yourself\b/i,
    /\btake my life\b/i,
    /\btake your life\b/i,
    /\bkys\b/i,
    // General Slur
    /\bbastard\b/i,
    /\bwtf\b/i,
    /\bpussy\b/i,
    /\bdick\b/i,
    /\bass\b/i,
    /\bhell\b/i,
    /\bcock\b/i,
    /\bshut up\b/i,
    /\bfuck\b/i,
    /\bbottleneck\b/i,
    /\bbitch\b/i,
    /\bfag\b/i,
    /\bfaggot\b/i,
    /\bmfk\b/i,
    /\bmotherfucker\b/i,
    /\bshit\b/i,
    /\bfucking\b/i,
    /\bstfu\b/i,
    /\bpedo\b/i,
    /\bwog\b/i,
    /\bfuckwit\b/i,
    /\bfucker\b/i,
    /\bfucked\b/i,
    /\bdeadass\b/i,
    /\bblack guy\b/i,
    /\bukraine\b/i,
    // Politics
    /\bwar\b/i,
    /\bisrael\b/i,
    /\brussia\b/i,
    /\brussian\b/i,
    /\bhamas\b/i,
    /\bukraine\b/i,
    /\btrump\b/i,
    /\bbiden\b/i,
    /\blibtard\b/i,
    /\bredneck\b/i,
    /\bdemocrat\b/i,
    /\brepublican\b/i,
    /\bliberal\b/i,
    /\bconservative\b/i,
    /\bsocialist\b/i,
    /\bcapitalist\b/i,
    /\banarchist\b/i,
    /\bgovernment\b/i,
    /\bpolitics\b/i,
    /\belection\b/i,
    /\bcongress\b/i,
    /\bsenate\b/i,
    /\bparliament\b/i,
    /\bpresident\b/i,
    /\bprime minister\b/i,
    /\bdictator\b/i,
    /\bleader\b/i,
    /\bpartisan\b/i,
    /\bactivist\b/i,
    /\blobbyist\b/i,
    /\bpolitical party\b/i,
    /\bpolitical ideology\b/i,
    /\brevolution\b/i,
    /\bgovernmental\b/i,
    /\bideological\b/i,
    /\bopposition\b/i,
    /\bcentrist\b/i,
    /\bradical\b/i,
    /\bextremist\b/i,
    /\bprogressive\b/i,
    /\bneoconservative\b/i,
    /\bneoliberal\b/i,
    /\bsocial democrat\b/i,
    /\bauthoritarian\b/i,
    /\btotalitarian\b/i,
    /\blibertarian\b/i,
    /\bgreen party\b/i,
    /\bteaparty\b/i,
    /\banarchy\b/i,
    /\blaissez-faire\b/i,
    /\bfederalism\b/i,
    /\bstatism\b/i,
    /\bactivism\b/i,
    /\bleft-wing\b/i,
    /\bright-wing\b/i,
    /\bcentrism\b/i,
    /\bdemocracy\b/i,
    /\btotalitarianism\b/i,
    /\bpopulism\b/i,
    /\bislamist\b/i,
    /\bfeminism\b/i,
    /\bcommunism\b/i,
    /\bfascism\b/i,
    /\bsocial democracy\b/i,
    /\bcapitalism\b/i,
    /\bmarxism\b/i,
    /\bsocialism\b/i,
    /\banarchism\b/i,
    /\bnationalism\b/i,
    /\bglobalism\b/i,
    // Racial Slur
    /\bwall jumper\b/i,
    /\bcamel rider\b/i,
    /\bching chong\b/i,
    /\bwetback\b/i,
    /\bnigga\b/i,
    /\bnigger\b/i,
    /\bchink\b/i,
    /\bwhite trash\b/i,
    /\bbeaner\b/i,
    /\bbeany\b/i
];
module.exports = badWords;