name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Skip actions and go to run
        if: false
        run: echo "This won't be executed"

      - name: Start index.js with pm2
        run: |
          npm start index.js
