name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Start index.js with pm2
        id: start-app
        run: |
          npm start index.js
        continue-on-error: true

      - name: Check if the previous step failed
        if: steps.start-app.outcome != 'success'
        run: echo "The previous step failed. You can add your retry logic here."
